fail_fast: true  # pre-commit will stop running hooks after the first failure.
default_stages: [ commit, push ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
        # confilict with documentation generation
#      - id: trailing-whitespace
#        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: black
        entry: black
        types: [ python ]
        args: [ --line-length=100 ]

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        name: autoflake
        args: [ --in-place, --remove-all-unused-imports, --ignore-init-module-imports ]

#  - repo: https://github.com/pycqa/pydocstyle
#    rev: 6.3.0  # pick a git hash / tag to point to
#    hooks:
#      - id: pydocstyle
#        files: th2_data_services
#        args:
#          - --convention=google
#          - --add-ignore=D100,D101,D104,D105,D403, D102,   # http://www.pydocstyle.org/en/stable/error_codes.html

  - repo: local
    hooks:

      - id: unit_tests
        name: unit_tests
#        stages: [ push ]  # Don't work in my PyCharm for some reason.
        stages: [ commit ]
        entry: python -m pytest test --ignore test/test_recon_ob.py
        language: python
        pass_filenames: false
        always_run: true
        # Don't know how to solve the libs problem other way.
        additional_dependencies: [pytest]
